services:
  localstack:
    image: localstack/localstack:3
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DEBUG=1
      - PERSISTENCE=1
    volumes:
      - "./tmp/localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  postgres:
    image: postgres:16
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=devpass
      - POSTGRES_DB=pipeline
    volumes:
      - "./tmp/pgdata:/var/lib/postgresql/data"